# Generated by Django 5.0.4 on 2024-06-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
