# Generated by Django 5.0.4 on 2024-06-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedfile_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
