# Generated by Django 5.0.4 on 2024-06-30 12:22

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(),
        ),
    ]
