# Generated by Django 5.0.4 on 2024-07-01 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_fileshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
